#!/sbin/sh

ver=
tmp=/tmp/mipay-apps
default_prop=/system/build.prop

if [ "$3" ]; then
    zip=$3
    console=/proc/$$/fd/$2
    # write the location of the console buffer to /tmp/console for other scripts to use
    echo "$console" > /tmp/console
else
    console=$(cat /tmp/console)
    [ "$console" ] || console=/proc/$$/fd/1
fi

print() {
    if [ "$1" ]; then
        echo "ui_print $1" > "$console"
    else
        echo "ui_print  " > "$console"
    fi
    echo
}

abort() {
    [ "$1" ] && {
        print "Error: $1"
        print "Aborting..."
    }
    cleanup
    print "Failed to install mipay addons!"
    exit 1
}

cleanup() {
    [ "$zip" ] && rm /tmp/console
    [ -d "$tmp" ] && rm -rf "$tmp"
}

extract() {
    rm -rf "$2"
    mkdir -p "$2"
    unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
}

setperm() {
    find "$3" -type d -exec chmod "$1" {} \;
    find "$3" -type f -exec chmod "$2" {} \;
}

setprop() {
    if grep -q "^[[:space:]]*$1[[:space:]]*=" "$default_prop"; then
        sed -i "s/^[[:space:]]*$1[[:space:]]*=.*$/$1=$2/g" "$default_prop"
    else
        echo "$1=$2" >> "$default_prop"
    fi
}

print "****************************"
print "* MIUI 9 (EU) MiPay Addons *"
print "****************************"
print "version: $ver"

print "Mounting filesystems..."
mount /system
if mount | grep ro | grep -q /system; then
    mount -o remount,rw /system || print "Failed to mount read-write!"
    print 'Remount as read-write...'
fi

[ "$zip" ] && {
    extract "$zip" "$tmp"
}
cd "$tmp"

app_list=""
for f in ./system/app/*; do
    app_list="${app_list} /system/app/$(basename $f)"
done

print "Clean files..."
rm -rf $app_list

print "Adding files..."
cp -R ./system/app/* /system/app/ || abort "Failed copy apps"
#mkdir_symlink

print "Setting correct permissions..."
for f in $app_list; do
    print "Fixing permission: $f"
    setperm 0755 0644 $f
done
#do_symlink

print "Fixing build.prop for MiPay..."
setprop "ro.se.type" "eSE,HCE,UICC" || abort "Failed to patch build.prop"

umount /system
cleanup
print "Finished!"
