#!/sbin/sh

ver=
tmp=/tmp/cleaner-fix-apps

if [ "$3" ]; then
    zip=$3
    console=/proc/$$/fd/$2
    # write the location of the console buffer to /tmp/console for other scripts to use
    echo "$console" > /tmp/console
else
    console=$(cat /tmp/console)
    [ "$console" ] || console=/proc/$$/fd/1
fi

print() {
    if [ "$1" ]; then
        echo "ui_print $1" > "$console"
    else
        echo "ui_print  " > "$console"
    fi
    echo
}

abort() {
    [ "$1" ] && {
        print "Error: $1"
        print "Aborting..."
    }
    cleanup
    print "Failed to install xiaomi.eu rom fix!"
    exit 1
}

cleanup() {
    [ "$zip" ] && rm /tmp/console
    [ -d "$tmp" ] && rm -rf "$tmp"
}

extract() {
    rm -rf "$2"
    mkdir -p "$2"
    unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
}

setperm() {
    find "$3" -type d -exec chmod "$1" {} \;
    find "$3" -type f -exec chmod "$2" {} \;
}

try_del() {
    app=/system/$1
    if [ -d $app ]; then
        print "Removing ${app}..."
        rm -r "$app" || print "failed to remove $app"
    else
        print "Skipping ${app}"
    fi
}

force_encrypt_oreo() {
    fstab=/system/vendor/etc/fstab.qcom
    if ! [ -f "$fstab" ]; then
        print "No fstab.qcom in vendor, skipping..."
    else
        sed -i "
            s/\b\(encryptable\)=/fileencryption=/g
        " "$fstab"
        if ! grep -q '=ice,quota' "$fstab"; then
            sed -i "s/=ice/=ice,quota/g" "$fstab"
        fi
        echo "Enabled force encryption for /data"
    fi
}

print "***************************"
print "* MIUI 9 (EU) Cleaner Fix *"
print "***************************"
print "version: $ver"

print "Mounting filesystems..."
mount /system
if mount | grep ro | grep -q /system; then
    mount -o remount,rw /system || print "Failed to mount read-write!"
    print 'Remount as read-write...'
fi

[ "$zip" ] && {
    extract "$zip" "$tmp"
}
cd "$tmp"

app_list=""
for f in ./system/priv-app/*; do
    app_list="${app_list} /system/priv-app/$(basename $f)"
done

print "Clean files..."
rm -rf $app_list

print "Adding files..."
cp -R ./system/priv-app/* /system/priv-app/ || abort "Failed to copy apps"

print "Setting correct permissions..."
for f in $app_list; do
    print "Fixing permission: $f"
    setperm 0755 0644 $f
done

print "Removing evil apps..."
try_del app/MiuiDaemon

print "Enabling force encryption for Oreo..."
force_encrypt_oreo

umount /system
cleanup
print "Finished!"
